version: '3.4'
services:
  grafana:
    image: grafana/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=password1
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml     

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
     - ./loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml

  # If enabled, add database backup PlatformDB_GameEngine.bak in build/sqlserver/ folder
  #sqlserver:
  #  image: gameengine.sql
  #  build:
  #    context: .
  #    dockerfile: sqlserver/Dockerfile
  #  environment:
  #    - SA_PASSWORD=Pass@word
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - ${SQL_PORT:-5433}:1433