version: '3.4'
services:
  paymentsmessageconsumerservice:
    image: ${DOCKER_REGISTRY:-luckia}/paymentsmessageconsumerservice:${TAG:-latest}
    build:
      context: ../
      dockerfile: src/PaymentsMessageConsumerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - PaymentsMessageConsumerServiceOptions__Database__ConnectionString=${Database__ConnectionString:-Server=sqlserver;Database=TradingDB_Bookmaking;User Id=sa;Password=Pass@word;Encrypt=False}
      - PaymentsMessageConsumerServiceOptions__Broker__ConnectionString=${Broker__ConnectionString:-amqp://guest:guest@haproxy:5672}
      - Jaeger__AgentHost=${Jaeger__Host:-jaeger}
      - Jaeger__AgentPort=${Jaeger__Port:-6831}
      - Jaeger__Endpoint=${Jaeger__Endpoint:-http://jaeger:14268}
      - Serilog__WriteTo__1__Args__Uri=${Loki__Endpoint:-http://loki:3100}
    ports:
      - "5048:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      #- sqlserver
      - haproxy
      - jaeger
      - loki
